apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: workflow-prepare
spec:
  selector:
    matchLabels:
      name: workflow-prepare
  template:
    metadata:
      labels:
        name: workflow-prepare
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - sleep infinity
        image: ubuntu
        name: c1
      initContainers:
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/samtools:1.15.1--h1170115_0
        name: init0
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/python:3.8.3
        name: init1
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/perl:5.26.2
        name: init2
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/khmer:3.0.0a3--py37haa7609a_2
        name: init3
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/bedtools:2.30.0--hc088bd4_0
        name: init4
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/bwa:0.7.17--hed695b0_7
        name: init5
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/fastqc:0.11.9--0
        name: init6
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/trim-galore:0.6.7--hdfd78af_0
        name: init7
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/mulled-v2-fe8faa35dbf6dc65a0f7f5d4ea12e31a79f73e40:8110a70be2bfe7f75a2ea7f2a89cda4cc7732095-0
        name: init8
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/picard:2.27.4--hdfd78af_0
        name: init9
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/mulled-v2-0560a8046fc82aa4338588eca29ff18edab2c5aa:5687a7da26983502d0a8a9a6b05ed727c740ddc4-0
        name: init10
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/mulled-v2-57736af1eb98c01010848572c9fec9fff6ffaafd:402e865b8f6af2f3e58c6fc8d57127ff0144b2c7-0
        name: init11
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/phantompeakqualtools:1.2.2--0
        name: init12
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/macs2:2.2.7.1--py38h4a8c8d9_3
        name: init13
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/r-base:3.5.1
        name: init14
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/ucsc-bedgraphtobigwig:377--h446ed27_1
        name: init15
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/deeptools:3.5.1--py_0
        name: init16
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/homer:4.11--pl526hc9558a2_3
        name: init17
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/mulled-v2-8186960447c5cb2faa697666dc1e6d919ad23f3e:3127fcae6b6bdaf8181e21a26ae61231030a9fcb-0
        name: init18
      - command:
        - sh
        - -c
        - exit 0
        image: ubuntu:20.04
        name: init19
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/mulled-v2-ad9dd5f398966bf899ae05f8e7c54d0fb10cdfa7:05678da05b8e5a7a5130e90a9f9a6c585b965afa-0
        name: init20
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/mulled-v2-2f48cc59b03027e31ead6d383fe1b8057785dd24:5d182f583f4696f4c4d9f3be93052811b383341f-0
        name: init21
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/subread:2.0.1--hed695b0_0
        name: init22
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/mulled-v2-8849acf39a43cdd6c839a369a74c0adc823e2f91:ab110436faf952a33575c64dd74615a84011450b-0
        name: init23
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/multiqc:1.13a--pyhdfd78af_1
        name: init24
      nodeSelector:
        cwsexperiment: 'true'
