apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: workflow-prepare
spec:
  selector:
    matchLabels:
      name: workflow-prepare
  template:
    metadata:
      labels:
        name: workflow-prepare
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - sleep infinity
        image: ubuntu
        name: c1
      initContainers:
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/samtools:1.15.1--h1170115_0
        name: init0
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/python:3.9--1
        name: init1
      - command:
        - sh
        - -c
        - exit 0
        image: ubuntu:20.04
        name: init2
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/blast:2.12.0--pl5262h3289130_0
        name: init3
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/bedtools:2.30.0--hc088bd4_0
        name: init4
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/bowtie2:2.4.4--py39hbb4e92a_0
        name: init5
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/snpeff:5.0--hdfd78af_1
        name: init6
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/fastp:0.23.2--h79da9fb_0
        name: init7
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/fastqc:0.11.9--0
        name: init8
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/mulled-v2-5799ab18b5fc681e75923b2450abaa969907ec98:87fc08d11968d081f3e8a37131c1f1f6715b6542-0
        name: init9
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/cutadapt:3.5--py39h38f01e4_0
        name: init10
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/mulled-v2-ac74a7f02cebcfcc07d8e8d1d750af9c83b4d45a:1744f68fe955578c63054b55309e05b41c37a80d-0
        name: init11
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/minia:3.2.6--h9a82719_0
        name: init12
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/abacas:1.3.1--pl526_0
        name: init13
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/spades:3.15.4--h95f258a_0
        name: init14
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/bandage:0.8.1--hc9558a2_2
        name: init15
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/quast:5.2.0--py39pl5321h2add14b_1
        name: init16
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/ivar:1.3.1--h089eab3_0
        name: init17
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/picard:2.27.4--hdfd78af_0
        name: init18
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/mosdepth:0.3.3--hdfd78af_1
        name: init19
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/mulled-v2-ad9dd5f398966bf899ae05f8e7c54d0fb10cdfa7:05678da05b8e5a7a5130e90a9f9a6c585b965afa-0
        name: init20
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/unicycler:0.4.8--py38h8162308_3
        name: init21
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/mulled-v2-ff46c3f421ca930fcc54e67ab61c8e1bcbddfe22:1ad3da14f705eb0cdff6b5a44fea4909307524b4-0
        name: init22
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/bcftools:1.15.1--h0ea216a_0
        name: init23
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/tabix:1.11--hdfd78af_0
        name: init24
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/mulled-v2-093691b47d719890dc19ac0c13c4528e9776897f:27211b8c38006480d69eb1be3ef09a7bf0a49d76-0
        name: init25
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/mulled-v2-1a35167f7a491c7086c13835aaa74b39f1f43979:6b5cffa1187cfccf2dc983ed3b5359d49b999eb0-0
        name: init26
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/snpsift:4.3.1t--hdfd78af_3
        name: init27
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/nextclade:2.2.0--h9ee0642_0
        name: init28
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/pangolin:4.1.1--pyhdfd78af_0
        name: init29
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/mulled-v2-77320db00eefbbf8c599692102c3d387a37ef02a:08144a66f00dc7684fad061f1466033c0176e7ad-0
        name: init30
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/multiqc:1.12--pyhdfd78af_0
        name: init31
      - command:
        - sh
        - -c
        - exit 0
        image: quay.io/biocontainers/multiqc:1.13a--pyhdfd78af_1
        name: init32
      nodeSelector:
        cwsexperiment: 'true'
