apiVersion: v1
kind: Pod
metadata:
  name: management
spec:
  containers:
  - name: management
    image: ubuntu
    command:
      - /bin/bash
      - "-c"
      - "sleep infinity"
    workingDir: /data
    volumeMounts:
      - mountPath: /data
        name: data
      - mountPath: /input
        name: input
    securityContext:
      runAsUser: 0
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: api-exp-data
  - name: input
    persistentVolumeClaim:
      claimName: api-exp-input
  securityContext:
    runAsUser: 0
