apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-exp-data
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50G
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-exp-input
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5G      
